server:
  port: 20011
  
eureka:
  port: 8761
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

spring:
  application:
    name: lottery-web-basic
#  thymeleaf:
#    prefix:
#      classpath:  /templates/,/static/
#  session:
#  	timeout:	10000000# Session timeout in seconds.
#  	store-type:	redis
#  	redis:
#  		host:	localhost
#  		port:	6379
#  		password:
