server:
  port: 20011
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

spring:
  thymeleaf:
    prefix:
      classpath:  /templates/,/static/
  application:
    name: lottery-web-basic
  cloud:
    config:
      profile:  dev
      uri:  http://localhost:8881
  session: 
  	timeout:	10000000# Session timeout in seconds.
  	store-type:	redis
  	redis:
  		host:	localhost
  		port:	6379
  		password:	
