eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  port: 8761
mybatis:
  mapperLocations: classpath:com.pinshi.lottery.mapper.*.xml
  typeAliasesPackage: com.pinshi.lottery.po
redis:
  maxIdle: 100
  maxTotal: 500
  minEvictableIdleTimeMillis: 30000
  platform: lottery
  poollist: 127.0.0.1:6379
  testOnBorrow: true
  timeBetweenEvictionRunsMillis: 30000
redisson:
  lockName: lottery
  connectionPoolSize: 100
  connectTimeout: 2000
  pingTimeout:  2000
  timeout:  2000

server:
  port: 8762
spring:
  application:
    name: lottery-service-basic
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: lvdaole
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,config
    connectionProperties: config.decrypt=true
    maxActive: 20
    initialSize: 10
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 200
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss SSS
    time-zone: GMT+8
    default-property-inclusion: non_null
rocketmq:
  nameServerAddress: 127.0.0.1:9876
  producer:
    group: 1111
  consumer:
    broadcast:
      group: 1113
      notify: true
      topicListenerListStr:
    cluster:
      group: 1112
      notify: true
      topicListenerListStr: test_topic:com.pinshi.lottery.controller.user.TestListener
auth:
  redis:
    key:
      type: NOMAL_AUTHORIZATION_KEY_
    token:
      type: NOMAL_AUTHORIZATION_TOKEN_
